name: authwebview
description: A Flutter package for OAuth authentication using WebView. Originally developed for Rapider.ai (https://www.rapider.ai). Supports PKCE, multiple providers, and secure token storage.
version: 2.1.0
homepage: https://github.com/hakanmertb/authwebview
repository: https://github.com/hakanmertb/authwebview

environment:
  sdk: ^3.5.0
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  http: ^1.2.2
  crypto: ^3.0.1
  device_info_plus: ^12.1.0
  package_info_plus: ^8.3.0
  flutter_inappwebview: ^6.1.5
dependency_overrides:
  webview_flutter_wkwebview: 3.17.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  mockito: ^5.4.4
  build_runner: ^2.4.8

flutter: